### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Milaan1337** [csakennijottunk/pendroid_2#2]
- [x] Pálya és nehézségi szint választó képernyő
    

- [x] külön pályák(más texturák)

    

- [x] külön nehézségi szint(enemy életerő növelése, több ellenség)

- [x] Meteor életerő és annak változása

- [ ] Védett bolygó életereje -- Vizualis megjelenitesre, textúrára vár.

- [x] Játék vége:

    a) Lejár az idő és nem pusztult el a bolygó ( GYŐZELEM)
    b) Elpusztult a bolygó (VERESÉG)
    gametable.gamestate visszaadja a kör sikerességét(true = win;false = lose)
